### ISSUE TITLE
Crypt filename on download

### ISSUE THREAD

**Issue by jkroepke** [nextcloud/files_versions_s3#1]
Hi

S3 versioning work fine. I able to download old versions of a file, but if I download the file in a browser it will be download with an crypt file name

![image](https://user-images.githubusercontent.com/1560587/66319597-aa2e5f80-e91d-11e9-862a-50fd852ba9d3.png)

Original filename: Bildschirmfoto 2019-10-02 um 12.59.47.png

I have to attach the file ending .png manually to view the picture locally.

Using S3 as primary storage. Using Chrome as browser.

**Comment by icewind1991** [comment]
Should be fixed with https://github.com/nextcloud/server/commit/c1b8cb2e210377a818daf3cf107313a3d2ac9ca2
