### ISSUE TITLE
Documentation for Configuration

### ISSUE THREAD

**Issue by SystemDefenstrator** [nextcloud/files_versions_s3#14]
Hi there,

I'm having some trouble getting this set up and was wondering if anyone can elaborate on the configuration. My Nextcloud instance is configured for S3 as primary storage, and it works well for us. I've installed this app, but I can't figure out how to enable it.

What is the configuration ID that is supposed to be used in the setup? Is it the IAM user? The Bucket ID? The ARN of the bucket?

Without this, my setup is currently giving me a 403 when I check files_versions_s3:status:

```
  Error executing "GetBucketVersioning" on "https://XXXXXXXXXXXXXXXX.amazonaws.com/?versioning"; AWS HTTP error: Client error: `GET https://XXXXXXXXX.XXXXXXX.amazonaws.com/?versioning` resulted in a `403 Forbidden` response:                                                                                               
  <?xml version="1.0" encoding="UTF-8"?>                                                                                                                                   
  <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>XXXXX (truncated...)                                                                         
   AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>                                                                                           
  <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>XXXXXXXXXXX</RequestId><HostId>XXXXXXXXXXXXXXXXXXXX</HostId></Error>         
```
Can anyone give me a hand with getting this set up?

Thanks!

**Comment by SystemDefenstrator** [comment]
I just figured this out by pulling the code apart. It came down to using primary as the ID and properly configuring the bucket for versioning.

In all, this seems to be working great so far.

**Comment by Christopher-Hayes** [comment]
Threw me off as well, wasn't sure what value it was expecting.

For anyone else arriving here - it looks like you just put the integer of the option you want from the `sudo nextcloud.occ files_versions_s3:status` output. In my case, it was `1`.
