### ISSUE TITLE
S3 Versioning and Nextcloud Versions apps

### ISSUE THREAD

**Issue by antonkarliner** [nextcloud/files_versions_s3#4]
Tried to google an answer, but no success:

If I install S3 Versioning app – so I have do disable the native Nextcloud Versions app? Or do they work together?

Thanks in advance for the answer!

**Comment by icewind1991** [comment]
Both have to be installed at the same time.

This app provides a backend implementation for the normal versions app

**Comment by pierreozoux** [comment]
I have a related question, I currently have s3, and versions installed.

If I install your app, will I loose old versions? Or will it be transparent?

Thanks for your help, and let me know if you prefer a new question?

**Comment by pierreozoux** [comment]
Okay, actually it was easy to test, It is transparent!

So you can activate s3_versions, you still have the old versions, and can rollback to them, amazing!

Thanks a lot for the nice work :)
