### ISSUE TITLE
I'm using it with DigitalOcean spaces, how to recover old versions with the web interface?

### ISSUE THREAD

**Issue by marco-fabbri** [nextcloud/files_versions_s3#6]
Hello,

I'm using your app with DigitalOcean spaces, how do I see old versions in the web interface?

Ciao
Marco

**Comment by marco-fabbri** [comment]
It started working after a while. Is there any way to recover deleted files with this app?

**Comment by icewind1991** [comment]
> It started working after a while. Is there any way to recover deleted files with this app?

No, this only provides versioning
